/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <android/sharedmem_jni.h>
#include <android/sharedmem.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h> /* mmap() is defined in this header */
#include <fcntl.h>
#include <string.h>
#include <memory.h>


#define MAX_JPEG_BUF_SIZE (200*1024)

/* Header for class com_project_jnigallery_NativeGallery */

#ifndef _Included_com_project_jnigallery_NativeGallery
#define _Included_com_project_jnigallery_NativeGallery
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
